### PR TITLE
Create_a_post_issue#5, #17, #18, #19

### PR DESCRIPTION
**Pull request by Shivansh175**
I made the page containing a form to create a post under the chapter section.
I have attached the Screenshots of UI for different window sizes :
Screenshot 2023-07-13 044643
Screenshot 2023-07-13 044721
Screenshot 2023-07-13 044830

### CODE REVIEW

**Comment by ughrima** [comment]
This is perfectly done! Great work! Just one minor addition. Make sure you highlight "Chapter" on the navbar. Below I have attached what I am talking about. 
image

**Comment by Shivansh175** [comment]
Done!

**Comment by ughrima** [comment]
> Done!

Share the sc again once you're done with it.

**Comment by Shivansh175** [comment]
Screenshot 2023-07-14 052711

**Comment by Shivansh175** [comment]
Now it's completed from my side...do check it once.

**Comment by Shivansh175** [comment]
Please check out my latest my latest commit.
I tried to solve three issues( Issue no. 5, 17 and 19 ) in it.

**Comment by ughrima** [comment]
> Please check out my latest my latest commit. I tried to solve three issues( Issue no. 5, 17 and 19 ) in it.

Can you attach screenshots for issue 5 and 19? 
issue 17 has been perfectly done ! great work

**Comment by Shivansh175** [comment]
Okay!
Here are Screen captures for issue 5 and 19....



Issue#5

Screenshot 2023-07-15 122750
Screenshot 2023-07-15 122824
Screenshot 2023-07-15 122700



Issue#19

Screenshot 2023-07-15 122547
Screenshot 2023-07-15 122618
Screenshot 2023-07-15 122458

**Comment by Shivansh175** [comment]
Here are the screenshots of Issue-18

Screenshot 2023-07-15 150127
Screenshot 2023-07-15 150158
Screenshot 2023-07-15 150220

**Comment by ughrima** [comment]
Perfectly done!

**Pull request merged**
