### PR TITLE
Navbar_and_footer_issue#6

### PR DESCRIPTION
**Pull request by Shivansh175**
Ive added the navbar and footer on a blank page as u told...
Here are the screenshots, please review

Screenshot 2023-07-15 163015
Screenshot 2023-07-15 162945

### CODE REVIEW

**Comment by ughrima** [comment]
remove the buttons and add techconnect beside the logo

**Comment by Shivansh175** [comment]
Okay

**Comment by Shivansh175** [comment]
Done!!

Screenshot 2023-07-15 170939

**Comment by ughrima** [comment]
perfect!

**Pull request merged**
