### PR TITLE
Landing_page_created_isuue#1

### PR DESCRIPTION
**Pull request by Shivansh175**
I have created the page and making the PR. I tried my best but feel free to to notify me about my flaws as I am just a learner.

### CODE REVIEW

**Comment by ughrima** [comment]
I have viewed your code, There are few minor changes I feel which are required. 
1) Make the page responsive in a more better manner. Visually. Right now the cards/boxes are coming one after the another in responsive view. Try that it comes one under the other. 
2) Add the required  color to the footer
3) Try to find the same fonts that have been used in the given design 
4) Increase the box size a little and decrease the font size for "TechConnect" slightly 
5) Add the same logo that was being used in the ui as of now (instead of the name) 

I would mention to look at the provided ui and look at the spacing and sizing of components. These are very small changes but since front end is all about visual appeal, they go a long way. Apart from all this, great work done! If you have any doubt anywhere, don't be hesitant to reach out. 

Also please note another participant is working on the issue and is at the same pace as yours. Points will only be rewarded to the participant who completes the work first as in mentor approves the issue and there are no pending improvements. So I would advise you to hurry up with the changes!

**Comment by Shivansh175** [comment]
I made another commit in that PR is that fine or I have to make a seperate PR? I'm a bit confused about it.
Also check out the changes made in 2nd commit.

**Comment by ughrima** [comment]
Shivansh there are few more changes to be done.
1) Currently the css of the page is overflowing because the scrollbar has come now. Remove the scrollbar ie work on the overflow.
2) the colour for blog and chapter boxes have been swapped. the orange gradient is for chapters and blue is for blog
3) the login and sign up button is too wide right now. make it smaller
4) make the chapter blog opportunities font bolder
5)  responsive looks good but TechConnect, blog, opportunities, chapter font needs to be bigger bolder.

**Comment by Shivansh175** [comment]
Okayy.
But...
As You suggested, I made the boxes stacked over one another(for small window size), in that case the contents of the page can't be restricted to just one page and scroll is mandatory in that case....but yes I'll remove the scroll from the normal window.
Is this okay?

**Comment by ughrima** [comment]
> Okayy. But... As You suggested, I made the boxes stacked over one another(for small window size), in that case the contents of the page can't be restricted to just one page and scroll is mandatory in that case....but yes I'll remove the scroll from the normal window. Is this okay?

Yeah for responsive, scroll is required and you implemented that well but for the main window scroll isnt required so from there you will have to remove it. 
also for further help, I will provide you the font names that are being used.
TechConnect - Vemanem Pro
for everything else - Outfit

**Comment by Shivansh175** [comment]
Okay.
Thanks for the font names...I was struggling finding them.

**Comment by Shivansh175** [comment]
I couldn't find the Vemanem Pro font but used a very similar font instead. If u could just provide me the font it'll be a great help.
I'm commiting new changes(except this font).

**Comment by ughrima** [comment]
> I couldn't find the Vemanem Pro font but used a very similar font instead. If u could just provide me the font it'll be a great help. I'm commiting new changes(except this font).

Yes the font you found works as well. The main window of the page looks done as well. A little sizing issue is there with responsive. 

So under media screens
1) Increase login sign up fonts, right now they look very small
2) make the distance between TechConnect and boxes 0 
3)increase TechConnect font size 
4) Make the Chapter Opportunities Blog heading more bigger and bolder. So that they are either the same size or bigger than the content. 

Only these few minor changes are there and then you'll be good to go! Hurry up :)

**Comment by Shivansh175** [comment]
I made another commit please check it out.

**Comment by Shivansh175** [comment]
*that font can't be bolder than that.

**Comment by Shivansh175** [comment]
Is it good now? check it please.

**Pull request merged**
