### PR TITLE
issues #3 and #4

### PR DESCRIPTION
**Pull request by Shivansh175**
I've added the Opportunity page described under issue#4, It was not a single screen page so I couldn't add screenshots so please do check it once.

### CODE REVIEW

**Comment by Shivansh175** [comment]
Hey I tried searching two more images for background..


Screenshot 2023-07-19 204810

Screenshot 2023-07-19 205408

In the first one I had to add a white background color to navbar to increase its visibility.
well, 2nd one is doing good I think.

**Comment by ughrima** [comment]
shivansh i still feel its a little crowded, but these are more shaper vectors no doubt, wdy think

**Comment by Shivansh175** [comment]
Yeah so now what do u wanna suggest now?

**Comment by Shivansh175** [comment]
btw first one seems quite fine to me with that background on navbar.

**Comment by ughrima** [comment]
> btw first one seems quite fine to me with that background on navbar.

i like that navbar mai what you did  but its just that vector cant be understood.

**Pull request merged**
